sudo: false
language: php

php:
- 7.3

before_script:
  - travis_retry composer install --no-interaction --prefer-source --no-progress --no-suggest
  - cp .env.example .env
  - php artisan key:generate

branches:
  only:
    - master

cache:
  directories:
    - vendor

script:
- vendor/bin/phpunit

after_success:
   - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then curl -s "$FORGE"; fi'
