name: composer update

on:
  schedule:
    - cron: '0 4 * * *' #UTC

jobs:
  composer_update_job:
    runs-on: ubuntu-latest
    name: composer update
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: composer update action
        uses: kawax/composer-update-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.ACTION_TOKEN }}
          GIT_NAME: kawax
          GIT_EMAIL: kawaxbiz@gmail.com
